@startuml
title UserDetailsBO - class diagram
package BOs{
    package UserDetailsBO{
        interface UserDetailsBO {
            +Id: number 
            +UserID: string 
            +Name: string 
            +Password: string 
            +BusinessUnitId: string 
            +BusinessUnitName: string 
            +Phone: string 
            +Email: string 
            +UniqueUserId: string 
            +IsLoggedIn: boolean 
            +Message: string 
            +UploadChanges: boolean 
            +DownloadLatest: boolean 
            +IsModified: boolean 
            +DeviceID: string 
            +CurrentDB: string 
            +DownloadCount: number 
            +DB_Pwd: string 
        }
    }
}
newpage
package BOs{
    package UserDetailsBO{
        interface UserDetailsBO {
            +Id: number 
            +UserID: string 
            +Name: string 
            +Password: string 
            +BusinessUnitId: string 
            +BusinessUnitName: string 
            +Phone: string 
            +Email: string 
            +UniqueUserId: string 
            +IsLoggedIn: boolean 
            +Message: string 
            +UploadChanges: boolean 
            +DownloadLatest: boolean 
            +IsModified: boolean 
            +DeviceID: string 
            +CurrentDB: string 
            +DownloadCount: number 
            +DB_Pwd: string 
        }
    }
} 
package Helpers{
    package CycleCountSqliteStorage{
        class CycleCountSqliteStorage{
            +createUserInLocalDB(db: SQLiteDatabase,user: UserDetailsBO): Promise<void>
            +updateUser(database: SQLiteDatabase,userRecord: UserDetailsBO,userId: string = ''): Promise<boolean>
        }
    }
}
UserDetailsBO <-- CycleCountSqliteStorage
@enduml